create table missions
(
    id bigint not null primary key generated by default as identity,
    title text not null,
    mission_type text not null,
    description text not null,
    terrain text not null,
    author_id bigint references users(id)
);